name: dslink_dart_etsdb
version: 0.0.1
description: A Dart implementation of etsdb originally written in Java.
author: Joel Trottier-Hebert <iamquebecois@gmail.com>

environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart
  di: '>=3.3.10 <4.0.0'
  meta: '>=1.0.4 <2.0.0'
dev_dependencies:
  test: '>=0.12.15+12 <0.13.0'
  mockito: '>=1.0.1 <2.0.0'
